config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :galleries, only: [:index]  do
    resources :art_pieces, only: [:index, :new, :create, :edit, :update ]
  end
  resources :art_pieces, only: [:destroy]
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art_piece.rb
class ArtPiece < ApplicationRecord
  belongs_to :gallery
  has_many_attached :photos

  validates :title, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :dimension, presence: true

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :first_name, validate: true
  attribute :last_name, validate: true
  attribute :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, validate: true

  def headers
    {
      #this is the subject for the email generated, it can be anything you want
      subject: "Demande d'informations/ formulaire de contact",
      to: 'sfacrousset@gmail.com',
      from: %("#{first_name}" "#{last_name}" <#{email}>)
      #the form will display the name entered by the user followed by the email
    }
  end
end

app/models/galerie.rb
class Galerie < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  has_one_attached :photo
  has_many :art_pieces, dependent: :destroy
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :art_pieces, dependent: :destroy
  has_one_attached :photo

  scope :sculptures, -> { where(name: "Entre Terre et Pierres")}

  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :admin])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :admin])
  end
end

app/controllers/art_pieces_controller.rb
class ArtPiecesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :new, :create, :destroy, :edit]
  # a modif pour autoriser new create et destroy seulement a admin
  before_action :set_art_piece, only: [:edit, :update, :destroy]

  def index
    @gallery = Gallery.find(params[:gallery_id])
    @art_pieces = ArtPiece.where(gallery: @gallery).order(year: :desc).order(title: :asc)
  end

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @art_piece = ArtPiece.new
  end

  def create
    @art_piece = ArtPiece.new(art_piece_params)
    @gallery = Gallery.find(params[:gallery_id])
    @art_piece.gallery = @gallery
    if @art_piece.save!
      redirect_to gallery_art_pieces_path(@gallery)
    else
      render :new
    end
  end

  def edit
    @gallery = Gallery.find(params[:gallery_id])
  end

  def update
    @art_piece.update(art_piece_params)
    redirect_to gallery_art_pieces_path(@art_piece.gallery)
  end

  def destroy
    @art_piece.destroy
    redirect_to gallery_art_pieces_path(@art_piece.gallery)
  end

  private

  def set_art_piece
    @art_piece = ArtPiece.find(params[:id])
  end

  def art_piece_params
    params.require(:art_piece).permit(:title, :description, :dimension, :year, :gallery_id, photos: [])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :new, :create]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    if @contact.deliver
      @contact = Contact.new # remettre à zero le formulaire
      # flash[:notice] = 'Merci pour votre message, je reviens vers vous très prochainement !'
      # pas de .now avec flach quand on redirect, seulement quand render
      redirect_to new_contact_path, notice: 'Merci pour votre message, je reviens vers vous très prochainement !'
    else
      flash.now[:alert] = "Votre message n'a pas été envoyé"
      render :new
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :message)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]

  def index
    @galleries = Gallery.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about, :contact ]

  def home
  end

  def about
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/art_pieces/edit.html.erb
<div class="container">
  <h2>Modifier une oeuvre</h2>
  <div class="formulaire">
    <%= simple_form_for ([@gallery, @art_piece]) do |f| %>
    <%= f.input :title, :label => "Titre", :placeholder => "titre de l'oeuvre" %>
    <%= f.input :year, :label => "Année de création", :placeholder => "2015" %>
    <%= f.input :dimension, :label => "Dimensions", :placeholder => "40×40" %>
    <%= f.input :description, :label => "Description", :placeholder => "Huile sur toile" %>
    <%= f.input :photos, as: :file,  input_html: { multiple: true } %>
    <%= f.submit "Enregistrer", class: "btn-blue" %>
  <% end %>
  </div>
  <div class="retour">
    <%= link_to "Retour à la galerie", gallery_art_pieces_path(@gallery), class: "btn-blue" %>
  </div>
</div>

app/views/art_pieces/index.html.erb
<% content_for :meta_title, "Sandrine Rousset artiste peintre et sculptrice" %>
<% content_for :meta_description, "Découvrez en détail les différentes oeuvres réalisées par Sandrine Rousset" %>
<% content_for :meta_image, cl_image_path("cover.jpg") %>

<div class="container">
  <h2><%= @gallery.name %></h2>
  <div class="art_pieces">
    <% @art_pieces.each do |art_piece|%>
      <div class="card-art-piece">

        <% if art_piece.photos.attached? %>
            <div class="art_piece-img" style="background-image: url('<%= cl_image_path art_piece.photos[0].key %>')" data-toggle="modal" data-target="#modal<%= art_piece.id %>">
            </div>
            <h4 ><%= art_piece.title %></h4>
            <% if user_signed_in? && current_user.admin? %>
              <div class="liens">
                <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, art_piece_path(art_piece), method: :delete, data: { confirm: "Are you sure?" } %>
                <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_gallery_art_piece_path(@gallery, art_piece) %>
              </div>
            <% end %>
            <!-- Modal -->
              <div class="modal fade" id="modal<%= art_piece.id %>" tabindex="-1" role="dialog" aria-labelledby="modal<%= art_piece.id %>Label" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="modal<%= art_piece.id %>Label"><%= art_piece.title %></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
               <!--        carousel -->
                      <div id="myCarousel-<%= art_piece.id %>" class="carousel slide carousel-fade" data-ride="carousel" >
                        <div class="carousel-inner">
                          <% art_piece.photos.each_with_index do |photo, index| %>
                            <% if index == 0 %>
                              <div class="carousel-item active">
                                <%= cl_image_tag photo.key, alt: "painting of #{art_piece.title}", class: "download"%>
                                <p>Dimensions (en cm): <%= art_piece.dimension %></p>
                                <p><%= art_piece.description %> </p>
                                <p>(<%= art_piece.year%>)</p>
                              </div>
                            <% else %>
                              <div class="carousel-item">
                                <%= cl_image_tag photo.key, alt: "painting of #{art_piece.title}", class: "download" %>
                              </div>
                            <% end %>
                          <% end %>
                        </div>
                        <% if art_piece.photos[1].nil? %>
                        <% else %>
                          <a class="carousel-control-prev" href="#myCarousel-<%= art_piece.id %>" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="carousel-control-next" href="#myCarousel-<%= art_piece.id %>" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        <% end %>
                      </div>
                    </div>
              <!--     fin carousel -->
                     <div class="modal-footer" data-turbolinks="false">  <!-- turbolinks false: la modal est fermée quand on revient sur la page ap avoir cliqué sur btn plus d'infos -->
                        <%= link_to "Plus d'informations", new_contact_path, class: "plus btn-blue" %>
                      <button type="button" class="btn btn-blue" data-dismiss="modal">Close</button>
                     </div>
                  </div>
                </div>
              </div>
              <!--      fin modal -->
          <% end %>
        </div>
    <% end %>
  </div>
  <% if @art_pieces.size > 9 %>
     <div class="ancre">
      <button class ='btn-blue titre'><i class="fas fa-chevron-up"></i></button>
    </div>
  <% end %>
  <% if user_signed_in? && current_user.admin? %>
    <div class="ajout">
      <!--   a modif pour ne rendre accessible qu'a admin -->
      <%= link_to "Ajouter une oeuvre", new_gallery_art_piece_path(@gallery), class: "btn-blue" %>
    </div>
  <% end %>
</div>

app/views/art_pieces/new.html.erb
<div class="container">
  <h2>Ajouter une nouvelle oeuvre</h2>
  <div class="formulaire">
    <%= simple_form_for ([@gallery, @art_piece]) do |f| %>
    <%= f.input :title, :label => "Titre", :placeholder => "titre de l'oeuvre" %>
    <%= f.input :year, :label => "Année de création", :placeholder => "2015" %>
    <%= f.input :dimension, :label => "Dimensions", :placeholder => "40×40" %>
    <%= f.input :description, :label => "Description", :placeholder => "Huile sur toile" %>
    <%= f.input :photos, as: :file,  input_html: { multiple: true } %>
    <%= f.submit "Enregistrer", class: "btn-blue" %>
  <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
<% content_for :meta_title, "Sandrine Rousset artiste peintre et sculptrice" %>
<% content_for :meta_description, "Contactez Sandrine Rousset pour obtenir plus d'informations sur son travail et ses oeuvres." %>
<% content_for :meta_image, cl_image_path("banner.jpg") %>

<div class="contact-container">
  <h2>Contact</h2>
  <div class="intro">
    <div class="contact-image" style='background-image: url("https://res.cloudinary.com/du5qhnalh/image/upload/v1602918282/contact-1_ife7vi.jpg")'>
    </div>
    <div class="contact-artiste">
      <%= cl_image_tag('Sandrine_2_roa0jl', crop: :fill, class: "photo-id") %>
      <p class="contact-texte">Vous souhaitez en savoir plus sur mon travail, ou obtenir des informations supplémentaires sur une oeuvre ?
         Remplissez le formulaire de contact, je vous répondrai dans les meilleurs délais !
      </p>
    </div>
  </div>
  <div class="form">
    <%= simple_form_for @contact do |f| %>

    <%= f.input :first_name, :required => true, :label => "Votre prénom" %>
    <%= f.input :last_name, :required => true, :label => "Votre nom" %>
    <%= f.input :email, :required => true, :label => "Votre email" %>
    <%= f.input :message, :as => :text, :required => true, :label => "Votre message", :input_html => {:rows => 6} %>
    <%= f.submit 'Envoyer', class: "btn-blue form-btn" %>
  <% end %>
  </div>
  <% if flash.any? %>
  <% flash.keys.each do |flash_key| %>
    <%- next if flash_key.to_s == 'timedout' %>
    <div class="alert-message <%= flash_key %>">
      <a class="close" data-dismiss="alert" href="#"> x</a>
      <%= flash.discard(flash_key) %>
    </div>
  <% end %>
<% end %>
</div>

app/views/contacts/new.html.erb
<% content_for :meta_title, "Sandrine Rousset artiste peintre et sculptrice" %>
<% content_for :meta_description, "Contactez Sandrine Rousset pour obtenir plus d'informations sur son travail et ses oeuvres." %>
<% content_for :meta_image, cl_image_path("cover.jpg") %>

<div class="contact-container">
  <h2>Contact</h2>
  <div class="intro">
    <div class="contact-image" style='background-image: url("https://res.cloudinary.com/du5qhnalh/image/upload/v1605436767/contact_ikdjpz.jpg")'>
    </div>
    <div class="contact-artiste">
      <%= cl_image_tag('Sandrine_2_roa0jl', crop: :fill, class: "photo-id") %>
      <p class="contact-texte">Vous souhaitez en savoir plus sur mon travail, ou obtenir des informations supplémentaires sur une oeuvre ?
         Remplissez le formulaire de contact, je vous répondrai dans les meilleurs délais !
      </p>
    </div>
  </div>
  <div class="form">
    <div class="form-content">
      <%= simple_form_for @contact do |f| %>

      <%= f.input :first_name, :required => true, :label => "Votre prénom" %>
      <%= f.input :last_name, :required => true, :label => "Votre nom" %>
      <%= f.input :email, :required => true, :label => "Votre email" %>
      <%= f.input :message, :as => :text, :required => true, :label => "Votre message", :input_html => {:rows => 6} %>
      <%= f.submit 'Envoyer', class: "btn-blue form-btn" %>
      <% end %>
    </div>
    <%= cl_image_tag "pot_oe9po6", alt: "chevalet", class: "pot" %>
  </div>

</div>

app/views/galleries/index.html.erb
<% content_for :meta_title, "Sandrine Rousset artiste peintre et sculptrice" %>
<% content_for :meta_description, "Visitez la galerie en ligne de Sandrine Rousset, et découvrez ses oeuvres et ses différents univers !" %>
<% content_for :meta_image, cl_image_path("cover.jpg") %>

<div class="container">
  <div class="galleries">
    <div class="gallery-paintings">
      <h2>GALERIE DE PEINTURES</h2>
        <% @galleries.each_with_index do |gallery, index| %>
          <% next if gallery.name == "Entre Terre et Pierres" %>
          <% if index.even? %>
            <div class="card-gallery">
              <div class="description">
                <p><%= gallery.description %></p>
              </div>
              <%= link_to gallery_art_pieces_path(gallery) do %>
              <div class="photo" data-turbolinks="false" style="background-image: url('<%= cl_image_path gallery.photo.key %>')">
                <span class="title"><%= gallery.name %></span>
              </div>
              <% end %>
            </div>
          <% else %>
            <div class="card-gallery-two">
              <%= link_to gallery_art_pieces_path(gallery) do %>
                <div class="photo-bis" data-turbolinks="false" style="background-image: url('<%= cl_image_path gallery.photo.key%>')">
                  <span class="title"><%= gallery.name %></span>
                </div>
              <% end %>
              <div class="description">
               <p><%= gallery.description %></p>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
    <div class="gallery-sculptures">
      <h2>GALERIE DE SCULPTURES</h2>
        <div class="card-gallery">
          <% @galleries.sculptures.each do |gallery| %>
            <div class="description">
              <p><%= gallery.description %></p>
            </div>
            <%= link_to gallery_art_pieces_path(gallery) do %>
              <div class="photo" style="background-image: url('<%= cl_image_path gallery.photo.key%>')">
                <span class="title"><%= gallery.name %></span>
              </div>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <%= favicon_link_tag "favicon.ico" %>
    <meta name="description" content="<%= meta_description %>">
    <!-- recharger la page home pour que l'animation parnethèse se fasse à chaque fois -->
    <% if (controller.controller_name == "pages" && controller.action_name == "home")%>
      <meta name="turbolinks-visit-control" content="reload" >
    <% end %>


    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <div class="main-container">
      <%= render 'shared/menu' unless (controller.controller_name == "pages" && controller.action_name == "home")%>
      <%= render 'shared/flashes' unless controller.controller_name == "contact" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :meta_title, "Sandrine Rousset artiste peintre et sculptrice" %>
<% content_for :meta_description, "Découvrez quelques pensées qui inspirent Sandrine Rousset dans son travail d'artiste" %>
<% content_for :meta_image, cl_image_path("cover.jpg") %>

<div class="about-container">
  <h2>Quelques mots</h2>
  <div class="image" style='background-image: url("https://res.cloudinary.com/du5qhnalh/image/upload/v1602610583/about_ofjnpn.jpg")'>
  </div>
  <div class="contenu">
    <%= cl_image_tag ("sand_rw6o9t"), crop: :fit, class: "portrait" %>
    <div class="texte">
      <p>Fantaisies, éclats, rêveries, moments suspendus, lieux indéfinis mais qui font écho, réminiscences…
        L’invitation aux voyages est là; voyage évocateur, intérieur, hors du temps, apaisant.
      Laissez-vous emporter au gré des couleurs, des atmosphères et imaginez votre histoire …
      <details>
        <summary>Plus d'informations</summary>
        <p>Pour en savoir un peu plus sur l'artiste, rendez-vous sur &ensp;
          <%= link_to '<i class="fab fa-facebook-f"></i>'.html_safe, "https://www.facebook.com/sandrine.rousset.507", :target => "_blank" %>
        </p>
      </details>
      </p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :meta_title, "Sandrine Rousset artiste peintre et sculptrice" %>
<% content_for :meta_description, "Bienvenue sur le site de Sandrine Rousset, artiste peintre et sculptrice" %>
<% content_for :meta_image, cl_image_path("cover.jpg") %>

<div class="home-navcolumn">
  <div class="artiste">
    <h1>SANDRINE ROUSSET</h1>
    <h3>Peintures&ensp;Sculptures</h3>
  </div>
  <div class="home-menu">
    <%= link_to "Quelques mots", about_path, class: "trait" %>
    <%= link_to "Galerie en ligne", galleries_path %>
    <%= link_to "Contact", new_contact_path, class: "trait-bis" %>
  </div>
  <div class="home-footer">
    <div class="navbar" style="display: none;">
      <%= render 'shared/navbar' %>
    </div>
    <%= link_to '<i class="fab fa-facebook-f"></i>'.html_safe, "https://www.facebook.com/sandrine.rousset.507", :target => "_blank" %>
  </div>
</div>

<div class="home-container" style='background-image: url("https://res.cloudinary.com/du5qhnalh/image/upload/v1605366834/banner_dll3qe.jpg")'>
  <!-- <h2 class="anim">-->
  <h2>
      <span class="one">P</span>
      <span id='two' class="anim_letter-1">a</span>
      <span id='two' class="anim_letter-2">r</span>
      <span id='two' class="anim_letter-3">e</span>
      <span id='two' class="anim_letter-4">n</span>
      <span id='two' class="anim_letter-5">t</span>
      <span id='two' class="anim_letter-6">h</span>
      <span id='two' class="anim_letter-7">è</span>
      <span id='two' class="anim_letter-8">s</span>
      <span id='two' class="anim_letter-9">e</span>
      <span id='two' class="anim_letter-10">s</span>&ensp;
      <span id='two' class="anim_letter-11">p</span>
      <span id='two' class="anim_letter-12">o</span>
      <span id='two' class="anim_letter-13">é</span>
      <span id='two' class="anim_letter-14">t</span>
      <span id='two' class="anim_letter-15">i</span>
      <span id='two' class="anim_letter-16">q</span>
      <span id='two' class="anim_letter-17">u</span>
      <span id='two' class="anim_letter-18">e</span>
      <span id='two' class="anim_letter-19">s</span>
  </h2>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<div class="navcolumn">
  <div class="artiste">
    <h1>SANDRINE ROUSSET</h1>
    <h3>Peintures&ensp;Sculptures</h3> <!-- crée un espace double -->
  </div>
<!--   <div class="trait"></div> -->
  <div class="menu">
    <%= link_to "Home", root_path, class: "trait" %>
    <%= link_to "Quelques mots", about_path %>
    <%= link_to "Galerie en ligne", galleries_path %>
    <%= link_to "Contact", new_contact_path, class: "trait-bis" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="btn-group dropup">
    <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Admin
    </button>
    <div class="dropdown-menu">
      <%= link_to "Modifier mon Profil", edit_user_registration_path, class: "dropdown-item" %>
      <%= link_to "Deconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </div>
  </div>
  <% else %>
    <%= link_to new_user_session_path do%>
      <div class="square">
      </div>
    <% end %>
<% end %>